# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: login dockerhub
      env:
        DockeruserName: ${{secrets.dockerUsername}}
        DockerPassWord: ${{secrets.dockerPassword}}
      run: docker login -u DockeruserName -p DockerPassWord

    - name: build docker Image
      run: docker build -t docker-push .

    - name: docker push into the repository
      run: docker push bala4399/docker-push:latest 
      
    
        
        
