# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: login dockerhub
      env:
        DockeruserName: ${{ secrets.DOCKERUSERNAME }}
        DockerPassWord: ${{ secrets.DOCKERPASSWORD }}
      # run: echo "$DockerPassWord" | docker login -u "$DockeruserName" --password-stdin #security
      run: docker login -u $DockeruserName -p $DockerPassWord #security
    - name: build docker Image
      run: docker build -t bala04031999/docker-push .

    - name: push to dockerhub
      run: docker push bala04031999/docker-push:latest 
      
    
        # 
        
